// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmm9dvleKAw-MIlINQ_tcdrTmSqzUdsBI',
    appId: '1:267350328218:web:672f2a36d78e6041c1f023',
    messagingSenderId: '267350328218',
    projectId: 'app-mmxxii',
    authDomain: 'app-mmxxii.firebaseapp.com',
    storageBucket: 'app-mmxxii.appspot.com',
    measurementId: 'G-7HCGN47K3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWHYT7Sj_xSNHnTwMg8XB6R1c1qCiTOEU',
    appId: '1:267350328218:android:5dfdd8d45acef2f8c1f023',
    messagingSenderId: '267350328218',
    projectId: 'app-mmxxii',
    storageBucket: 'app-mmxxii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGqVgwnZj3q0C4cmn--JT5MGm4c2gom-Q',
    appId: '1:267350328218:ios:193552ada9581901c1f023',
    messagingSenderId: '267350328218',
    projectId: 'app-mmxxii',
    storageBucket: 'app-mmxxii.appspot.com',
    iosClientId: '267350328218-bv1iko4ldhkf9egrr7itrl4400l8qmqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.managementapp',
  );
}
